language: python
python:
  - 2.6
  - 2.7
  - 3.4
matrix:
  allow_failures:
    - python: 3.4
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
install:
  - npm install -G socket.io@0.9
  - pip install -U --use-mirrors requests
  - pip install -U --use-mirrors six
  - pip install -U --use-mirrors websocket-client
before_script:
  - node serve-tests.js
  - sleep 1
script: nosetests
